### ISSUE TITLE
Fix ghpages deploy job

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/vscode-theia-comparator#6] opened 2021-12-17 10:20 UTC
It seems the last time we ran the travis job to deploy a nightly comparison to github pages ran in June. We need to make this run nightly again. Maybe switch to github pages in the process to reduce external dependencies.

**Comment by lucas-koehler** [comment] 2022-01-05 08:39
With the merged PR, the updated report is now available via Github pages at https://eclipse-theia.github.io/vscode-theia-comparator/status.html

I think we can now remove the `.travis.yml` file because the new setup uses Github Actions instead.

**Comment by vince-fugnitto** [comment] 2022-01-15 19:30
> I think we can now remove the `.travis.yml` file because the new setup uses Github Actions instead.

The `.travis.yml` file was removed as part of https://github.com/eclipse-theia/vscode-theia-comparator/pull/8.
The repo now uses github actions so I believe the issue is closeable.

**Closed by vince-fugnitto** 2022-01-15 19:30 UTC
