### ISSUE TITLE
VS Code API compatibility of ProviderResult

### ISSUE THREAD

**Issue by planger** [eclipse-theia/vscode-theia-comparator#21] opened 2022-04-19 14:11 UTC
The [vscode-theia-comparator report](https://eclipse-theia.github.io/vscode-theia-comparator/filtered-status.html) shows `ProviderResult` as incompatible on master, but considered it as compatible in the last Theia release.

This seems to be related to change https://github.com/eclipse-theia/theia/commit/e6b57ba4edabf797f3b4e67bc2968cdb8cc25b1e, after which it is defined as follows in Theia:
```typescript
export type ProviderResult<T> = T | undefined | null | Thenable<T | undefined | null>; 
```

In VS Code it is defined as follows (ie equivalent to how it is now in Theia):
```typescript
export type ProviderResult<T> = T | undefined | null | Thenable<T | undefined | null>;
```

Before the change linked above, it was defined as follows in Theia and was deemed OK:
```typescript
export type ProviderResult<T> = T | undefined | PromiseLike<T | undefined>;
```

**Comment by sgraband** [comment] 2022-04-27 08:18
I can take a look.

**Comment by lucas-koehler** [comment] 2022-04-29 08:25
Hi @sgraband, unfortunately I don't know in detail where to look at but I can give you some initial pointers.

Some pointer where I'd try to see how it's parsed is in `parser.ts#serializeFunction`. See https://github.com/eclipse-theia/vscode-theia-comparator/blob/389faf3213afcd61cc5b177b440dbacb3f7b70c2/src/parser.ts#L100 to where Thenable and PromiseLike are replaced. I assume in the end the `hash` will be different for the new signature for some reason.
I'd also check around here in the comparator: https://github.com/eclipse-theia/vscode-theia-comparator/blob/master/src/comparator.ts#L234
This compares the hashs of two version entries. Might be a good point to debug to see the difference.

Also, I'm all for adding some debug configs to make investigating issues like this easier :)

**Comment by sgraband** [comment] 2022-05-02 11:20
So i was able to debug this a bit further. The issue seems to be that this line:
https://github.com/eclipse-theia/vscode-theia-comparator/blob/389faf3213afcd61cc5b177b440dbacb3f7b70c2/src/parser.ts#L146

evaluates to the correct type when parsing from the VSCode file, but evaluates to an `any` type when parsing the Theia file with the same typing as the VSCode file. As i highly doubt. that this method is not deterministic the issue is probably within the `symbol.declarations[0]`.

What i find strange is that it works for the VSCode file as there seems to be no difference between parsing VSCode API and the Theia API. Or is there something that i am missing?

**Comment by sgraband** [comment] 2022-05-25 11:07
Together with @lucas-koehler we were able to find the issue of this. The Thenable type is directly defined in the vscode-files but not in the theia-files. Therefore, the parser cannot get the type and instead returns `any`. So this is not directly a problem in the comparator, but rather in the API file itself. 

IMHO we should not use types, that aren't defined in typescript or the file itself, in the API files.

I would propose to change all `Thenable`s in the API file to `PromiseLike` as we should not mix between the two of them. @planger WDYT?

We also noticed, that the existing theia `Thenable`s (which all are return types) matched with the vscode methods. This is due to the fact, that methods with any return type will always match. I will open a follow up bug for this.

**Comment by planger** [comment] 2022-05-30 08:49
Thanks for investigating this issue!
Yes, I think switching all usages of `Thenable` to `PromiseLike` sounds like a good step towards consistency within the API. But best to also raise this issue in the Theia main repository and ask for feedback if anyone has objections.
Once you opened this issue in Theia, please link it here and close this one.
Thanks!

**Comment by sgraband** [comment] 2022-05-30 11:38
Opened https://github.com/eclipse-theia/theia/issues/11214 for this. Will close this!

**Closed** 2022-05-30 11:40 UTC
